### ISSUE TITLE
大佬手势这块能监听吗？

### ISSUE THREAD

**Issue by 54huige** [chinesejar/flutter_with_map#1]
事件这块大佬怎么做 表示不会原生开发

大佬会考虑做完善下这个百度地图插件吗

高德的有人在做 百度的还没遇到呢

**Comment by timeroute** [comment]
用 channel 来通信，可参考 [深入理解Flutter Platform Channel](https://juejin.im/post/5b84ff6a6fb9a019f47d1cc9)
